### ISSUE TITLE
no adapter removal with dovetailed alignments

### ISSUE THREAD

**Issue by czhu** [jsh58/NGmerge#11]
for the dovetailed alignments possible to retain the adapter sequences at both ends?

**Comment by jsh58** [comment]
It is not clear what you are asking.  If you want a separate file that lists the 3' overhang (putative adapter) sequences removed, please see the description of the [`-c <file>`](https://github.com/jsh58/NGmerge#stitch-output).  If you want the reads to retain the 3' overhangs, that is not possible.

**Comment by czhu** [comment]
I meant to retain both the 5' and 3' overhangs. To get them in a separate file is also fine. Thank you!
