### ISSUE TITLE
is there any option for batch processing?

### ISSUE THREAD

**Issue by foamy1881** [jsh58/NGmerge#13]
Is there an option to multi process in a loop for all R1 and R2 fastq inside a folder? I have more than 1000 fastqs to process.. Would be tedious to process them one by one.

**Comment by jsh58** [comment]
Thanks for the question.  It is easy to loop through files on the command-line.  See [this reference](https://www.cyberciti.biz/faq/bash-loop-over-file/) for examples of writing loops in bash, and [this reference](https://www.thegeekstuff.com/2010/07/bash-string-manipulation/) for string (filename) manipulation.
