### ISSUE TITLE
bioconda install

### ISSUE THREAD

**Issue by pdellorusso** [jsh58/NGmerge#14]
Hi, I went to install NGmerge through bioconda on an ubuntu terminal (operated on a Windows computer). I received the following error about solving the environment. This error is unique to NGmerge as I have been able to install several other packages through bioconda. I'm using the latest version of anaconda3 for linux x64 (https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh)

Thank you for your help!

> (ngmerge) passeguelab@BB11CSCI-M003:~$ conda install -c bioconda ngmerge
> 
> Collecting package metadata (current_repodata.json): \
> done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError:'

**Comment by pdellorusso** [comment]
I will also note that as a test, I was able to install NGmerge through bioconda on my mac.

**Comment by jsh58** [comment]
It is difficult to know what may be causing the problem in your environment.  You can try installing in [verbose mode](https://docs.conda.io/projects/conda/en/latest/commands/install.html):
```
-v, --verbose
  Can be used multiple times. Once for INFO, twice for DEBUG, three times for TRACE.
```
