### ISSUE TITLE
Merging problem

### ISSUE THREAD

**Issue by Behnaz64** [jsh58/NGmerge#15]
Hello

I'm trying to merge my paired end reads into a single read by NGmerge. The problem is when I run a command like 
 
NGmerge-master/NGmerge -1 AH1-R1.fastq -2 AH1-R2.fastq -o AH1-merged.fastq

the resultant merged file has a huge reduction in the file size and number of reads, for example from 600M to 70M, and from 15,000,000 reads to only 1,000,000 reads!

Could you please tell me what the issue reason might be?

Thank you

**Comment by jsh58** [comment]
If you run NGmerge in verbose mode with `-v`, you can see the counts of reads that are merged.

**Comment by Behnaz64** [comment]
Thank you for your helpful comment. Here is the outcome:

Processing files: AH1-R1-trimmed.fastq,AH1-R2-trimmed.fastq
  Fragments (pairs of reads) analyzed: 3211861
  Successfully stitched: 284993

Does it mean that there is a problem with most of my reads in FASTQ files that they cannot be stitched? Do you have any suggestion to fix the issue?

**Comment by jsh58** [comment]
If a pair of reads does not overlap, they cannot be merged.  Please read the [README](https://github.com/jsh58/NGmerge) and the [manuscript](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2).
