### ISSUE TITLE
Error! Input file does not follow fastq format

### ISSUE THREAD

**Issue by SWittouck** [jsh58/NGmerge#19]
Dear John,

When I run the following, I get "Error! Input file does not follow fastq format", although I am convinced that my input files are in fastq format ([reads.zip](https://github.com/jsh58/NGmerge/files/6344950/reads.zip)): 

`NGmerge -1 AMBV1527_forward.fastq -2 AMBV1527_reverse.fastq -o merged.fastq`

Any idea what the problem might be? 

Best regards,
Stijn

**Comment by jsh58** [comment]
Thanks for the question, and for including the reads.zip file.  It appears that your reads are longer than the `MAX_SIZE` allowed by NGmerge, which is 1024.  You should increase that value in [this line of `NGmerge.h`](https://github.com/jsh58/NGmerge/blob/master/NGmerge.h#L10), recompile the program, and then use it.

**Comment by SWittouck** [comment]
Thanks for the quick reply! I adapted the MAX_SIZE, recompiled, optimized some other parameters and now I got them to stitch.

Thank you very much for your help! 

Stijn
