### ISSUE TITLE
Error! Quality scores outside of set range

### ISSUE THREAD

**Issue by Balakulandai** [jsh58/NGmerge#23]
Hi everyone
I run the command 
./NGmerge  -1 /home/planktonecology/Manuscript_Thatha/Metagenome_Thatha/CG_DN_935/AST5_R1.fastq.gz  -2 /home/planktonecology/Manuscript_Thatha/Metagenome_Thatha/CG_DN_935/AST5_R2.fastq.gz  -o AST5_merged.fastq.gz

I got error as follows
Error! Quality scores outside of set range

**Comment by KuechlerO** [comment]
Take a look here:
[(https://github.com/jsh58/NGmerge/issues/4)]

More specifically:

>  I have the same issue, and it is not solved by setting '-u 41' by itself: The -w parameter must also be supplied with a modified qual_profile.txt. Modifying the matrixes with an extra row and column worked (I simply copied the outermost values).
