### ISSUE TITLE
Error! sample: unknown command-line argument

### ISSUE THREAD

**Issue by Julio92-C** [jsh58/NGmerge#24]
Hi, I am trying to use this tool, but after running the following command:

$NGmerge -1 $FILE2  -2 $FIL3 -o sample -a -n 20 -v

I got this: Error! sample: unknown command-line argument

I cannot figure out where the error come from. I will appreciate your help.

Thanks in advance.

**Comment by jsh58** [comment]
this could occur if `$FIL3` is not defined (maybe it should be `$FILE3`?)

**Comment by Julio92-C** [comment]
Thanks for your reply. It works now.

Julio :)
