### ISSUE TITLE
Error! -2 cannot open file for reading

### ISSUE THREAD

**Issue by santiago-es** [jsh58/NGmerge#25]
Getting a very bizarre Error! -2 cannot open file for reading when trying to run Ngmerge in stitch mode **_but only when NGmerge is run via a SLURM batch script_** 

If I run the exact same NGMerge command (./NGmerge -1 r1.fq -2 r2.fq -o output.fq, e.g.) through the interactive command line, works no problem

If I take that same command and run it as a part of a bash submission script for a SLURM job on a HPCC it fails with Error! -2 cannot open file for reading

It looks like theres some issue when it attempts to stat both files into memory?

**Comment by jsh58** [comment]
I have not observed any issue like that with NGmerge.  Maybe you should try running your batch script from the command line, without submitting to SLURM.  Then you can see if there is an issue with your script, or with SLURM/HPC.
