### ISSUE TITLE
Undertanding how merged read when bases unmatched

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [jsh58/NGmerge#27]
Hello, 

I am not able to understand this

```
CCCTCGTACTAGTTAAAGTGGCCTAAGAAGACGACACATGAGAGCGAGAA GGG ATGCCCAAAGCTGTCGTTTGTTACAAAGCCGCATAGCTTGATGATGTTGG R1
CCAACATCATCAAGCTATGCGGCTTTGTAACAAACGACAGCTTTGGGCAT AAA TTCTCGCTCTCATGTGTCGTCTTCTTAGGCCACTTTAACTAGTACGAGGG R2
CCCTCGTACTAGTTAAAGTGGCCTAAGAAGACGACACATGAGAGCGAGAA GGT ATGCCCAAAGCTGTCGTTTGTTACAAAGCCGCATAGCTTGATGATGTTGG merged with NGmerge


CCCTCGTACTAGTTAAAGTGGCCTAAGAAGACGACACATGAGAGCGAGAA GGG ATGCCCAAAGCTGTCGTTTGTTACAAAGCCGCATAGCTTGATGATGTTGG R1
CCAACATCATCAAGCTATGCGGCTTTGTAACAAACGACAGCTTTGGGCAT AAA TTCTCGCTCTCATGTGTCGTCTTCTTAGGCCACTTTAACTAGTACGAGGG R2
CCCTCGTACTAGTTAAAGTGGCCTAAGAAGACGACACATGAGAGCGAGAA TTT ATGCCCAAAGCTGTCGTTTGTTACAAAGCCGCATAGCTTGATGATGTTGG merged with PEAR 
```

These are simulated reads I have created to understand and compare these programs. I cannot figure out why in your program, a T is added when R1 has a G and R2 an A. Almost similar happens with PEAR.

I provide the command used in both programs

```bash
pear \
-f simulated_R1_dif.fastq \
-r "simulated_R2_dif.fastq \
-o pear_output.fastq


apptainer run ngmerge_latest.sif \
/bin/bash -c "cd /NGmerge && NGmerge \
-1 simulated_R1_dif.fastq" \
-2 simulated_R2_dif.fastq" \
-o /merged.fastq"
```

**Comment by jsh58** [comment]
What are the quality scores of your simulated reads?

**Comment by Manuel-DominguezCBG** [comment]
For these bases 

CCCTCGTACTAGTTAAAGTGGCCTAAGAAGACGACACATGAGAGCGAGAA

And these one

ATGCCCAAAGCTGTCGTTTGTTACAAAGCCGCATAGCTTGATGATGTTGG

The quality is 40.

And for the three bases in the middle of the read, the quality is all possible combinations (0-0, 0-1, 0-2...1-0,1-1...40,40). Independely the quality of these three bases,  the result is always GGT.

Why the quality of the base in R1 and R2 would introduce a new base?

**Comment by jsh58** [comment]
I refer you to "Note S2: Methods for producing a merged read" from [Additional file 1](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2#Sec14) of the NGmerge manuscript:

- All the merging programs, including NGmerge, select the base with the higher quality score when the R1 and R2 bases disagree.

- In cases where the quality scores are equal:
   > NGmerge selects the base that is closer to its read’s 5’ end, whereas the other three merging programs [including PEAR] automatically use the R2 base.

So `GGT` would be the expected outcome with equality quality scores. Note that `T` is the complement of `A`.

**Comment by Manuel-DominguezCBG** [comment]
Excellent. I missed that document when I read the paper. Thank you so much. I close the issue
