### ISSUE TITLE
Error! Quality score file missing values for score range

### ISSUE THREAD

**Issue by kingdynasty** [jsh58/NGmerge#4]
My fastq file is Illumina-1.8 Phred+33 format, how to solve this problem?

**Comment by jsh58** [comment]
As described [here](https://github.com/jsh58/NGmerge#stitch-qual), the quality score profiles of `NGmerge` are limited to the range [0, 40].  If you have scores outside that range, you would need to provide alternative profiles.  This can be accomplished by modifying [`qual_profile.txt`](https://github.com/jsh58/NGmerge/blob/master/qual_profile.txt), adding rows and columns to each matrix.

**Comment by mchimenti** [comment]
kingdynasty, I had this same issue.  Let me give a clearer answer: 

You need to use Phred+33 (0,41).  That means setting '-u 41' instead of the default (40).  This will allow "J" to be an acceptable quality score character.

**Comment by tiantaibird** [comment]
> As described [here](https://github.com/jsh58/NGmerge#stitch-qual), the quality score profiles of `NGmerge` are limited to the range [0, 40]. If you have scores outside that range, you would need to provide alternative profiles. This can be accomplished by modifying [`qual_profile.txt`](https://github.com/jsh58/NGmerge/blob/master/qual_profile.txt), adding rows and columns to each matrix.

I have the same issues. What numbers shoul I add for the rows and columns to each matrix?

**Comment by marcgall** [comment]
I have the same issue, and it is not solved by setting '-u 41' by itself: The -w parameter must also be supplied with a modified qual_profile.txt. Modifying the matrixes with an extra row and column worked (I simply copied the outermost values). But isn't it odd that this problem crops up for such a common quality scheme?

**Comment by jsh58** [comment]
Not odd at all; the matrices were created by analyzing sequence data that was limited to [0, 40] (cf. [Figure 2](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2/figures/2)).

**Comment by czhu** [comment]
can you provide an option for quality score 41 since this is so common nowadays? I get the reason but it's quite common now to have Illumina 1.9 quality score, this issue really prevent us from using this nice tool.

**Comment by damienmarsic** [comment]
I tried NGmerge for the first time today and I have the same problem. the option '-u 41' does not help. Adding a row and a column to qual_profile.txt does not help either, unless I did not do it correctly. It would be nice to have a valid qual_profile.txt file to download.

**Comment by Jdbeck66** [comment]
Same issue. Seems like some explanation of how a custom `profile` is constructed would be a useful addition to the documentation. Suggesting that adding rows and columns to the matrix probably isn't sufficiently detailed to be helpful and pointing to a chart as the basis for the default profile doesn't indicate how that data was used to create the profile. This tool is a really useful tool for getting the relative abundances correctly identified in my downstream counting algorithms - so I'm hopeful you'll see this as a useful suggestion.

**Comment by jsh58** [comment]
The format of a file with custom quality score profiles is described in the README under [`-w <file>`](https://github.com/jsh58/NGmerge#quality-score-profile-options-).  The process of creating the default profiles is thoroughly described in the [NGmerge manuscript](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2).

**Comment by damienmarsic** [comment]
Easy fix: add both -u 41 and -g arguments.
Example:
NGmerge -1 Reads_1.fq.gz -2 Reads_2.fq.gz -o Merged_reads.fq.gz -u 41 -g

**Comment by splaisan** [comment]
worked for me too for aviti data where Qval climb up to 50

```
NGmerge -1 Reads_1.fq.gz -2 Reads_2.fq.gz -o Merged_reads.fq.gz -u 50 -g
```
