### ISSUE TITLE
qual_profile

### ISSUE THREAD

**Issue by tiantaibird** [jsh58/NGmerge#7]
My fastq file is Illumina-1.8 Phred+33 format, so I need to edit qual_profile.txt to expand the score range. What numbers in the rows and columns should I add to each "match" and "mismatch" matrix in the file?

**Comment by jsh58** [comment]
Thanks for the question.  As described in the [manuscript](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2), the `match` and `mismatch` matrices were created based on detailed analyses of datasets whose maximum phred scores were 40.  Therefore, there is no empirical basis on which to recommend matrix values beyond 40.  Perhaps, you can try extrapolating values by visually inspecting [Figure 3](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2579-2/figures/3).
