### ISSUE TITLE
NGmerge failing if read IDs are indicated by a forward slash

### ISSUE THREAD

**Issue by transcript** [jsh58/NGmerge#9]
Hello, I'm working on merging HMP data, where read IDs in forward vs. reverse reads are delineated by a forward slash, "/".

For example, the first read is @HWI-EAS319_616WC:3:100:10067:14224/1 in the forward reads and @HWI-EAS319_616WC:3:100:10067:14224/2 in the reverse reads.  Other mergers have been able to accommodate this, but NGmerge reports these as different reads and fails.

Is there a method to adjust for these?  Is there a different forward/reverse read delineator that NGmerge expects?

**Comment by jsh58** [comment]
Thanks for the question.  NGmerge expects paired reads' headers to match up to the first space character (or to the end of the line).  You can change the delimiter to `/` by editing the code on [line 153](https://github.com/jsh58/NGmerge/blob/master/NGmerge.c#L153):
```
    } else if (head1[j] == '/')
```
and similarly on line 157.  Recompile the program, and you should be all set.

**Comment by transcript** [comment]
Thanks, that works great!  I made the change, tested it to confirm that it functions, and added a pull request with the additional feature (added an else if, instead of removing the space, so it should be able to handle both cases).
